Public Enum ConfigurationTypeEnum
    [Short] = 0
    [Resume] = 1
    Complete = 2
End Enum

Module modConfigurations

    Public Function [Short]() As XmlDocument
        Dim pXmlDocument As New XmlDocument
        pXmlDocument.AppendChild(pXmlDocument.CreateProcessingInstruction("xml", "version='1.0' encoding='utf-8'"))

        Dim pSystemInfo As XmlElement = pXmlDocument.CreateElement("SystemInfo")
        pSystemInfo.SetAttribute("Type", "Resume")
        pXmlDocument.AppendChild(pSystemInfo)

        Dim pXmlClass As XmlElement
        pXmlClass = AddItem(pSystemInfo, "Win32_Monitor")
        AddAttribute(pXmlClass, "Device")
        AddAttribute(pXmlClass, "ManufacturerID")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_1394Controller")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProtocolSupported")

        pXmlClass = AddItem(pSystemInfo, "Win32_BaseBoard")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Product")
        'AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_Battery")
        'AddAttribute(pXmlClass, "Availability")
        'AddAttribute(pXmlClass, "BatteryStatus")
        AddAttribute(pXmlClass, "Chemistry")
        AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DesignCapacity")
        AddAttribute(pXmlClass, "DesignVoltage")
        'AddAttribute(pXmlClass, "DeviceID")
        'AddAttribute(pXmlClass, "EstimatedChargeRemaining")
        'AddAttribute(pXmlClass, "EstimatedRunTime")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_BIOS")
        'AddAttribute(pXmlClass, "BiosCharacteristics")
        AddAttribute(pXmlClass, "BIOSVersion")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "ReleaseDate")
        'AddAttribute(pXmlClass, "SerialNumber")
        'AddAttribute(pXmlClass, "SMBIOSBIOSVersion")
        'AddAttribute(pXmlClass, "SMBIOSMajorVersion")
        'AddAttribute(pXmlClass, "SMBIOSMinorVersion")
        'AddAttribute(pXmlClass, "SoftwareElementState")
        'AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_CacheMemory")
        'AddAttribute(pXmlClass, "Associativity")
        'AddAttribute(pXmlClass, "Availability")
        'AddAttribute(pXmlClass, "BlockSize")
        'AddAttribute(pXmlClass, "CacheSpeed")
        'AddAttribute(pXmlClass, "CacheType")
        'AddAttribute(pXmlClass, "CurrentSRAM")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DeviceID")
        'AddAttribute(pXmlClass, "ErrorCorrectType")
        AddAttribute(pXmlClass, "InstalledSize")
        AddAttribute(pXmlClass, "Level")
        'AddAttribute(pXmlClass, "Location")
        AddAttribute(pXmlClass, "MaxCacheSize")
        'AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "NumberOfBlocks")
        AddAttribute(pXmlClass, "Purpose")
        'AddAttribute(pXmlClass, "SupportedSRAM")
        'AddAttribute(pXmlClass, "WritePolicy")

        pXmlClass = AddItem(pSystemInfo, "Win32_CDROMDrive")
        'AddAttribute(pXmlClass, "Availability")
        AddAttribute(pXmlClass, "Capabilities")
        'AddAttribute(pXmlClass, "CapabilityDescriptions")
        'AddAttribute(pXmlClass, "CompressionMethod")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "Drive")
        'AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "SCSIBus")
        'AddAttribute(pXmlClass, "SCSILogicalUnit")
        'AddAttribute(pXmlClass, "SCSIPort")
        'AddAttribute(pXmlClass, "SCSITargetId")

        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystem")
        'AddAttribute(pXmlClass, "ChassisBootupState")
        'AddAttribute(pXmlClass, "DNSHostName")
        'AddAttribute(pXmlClass, "Domain")
        'AddAttribute(pXmlClass, "InfraredSupported")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "NumberOfLogicalProcessors")
        AddAttribute(pXmlClass, "NumberOfProcessors")
        AddAttribute(pXmlClass, "OEMStringArray")
        AddAttribute(pXmlClass, "PCSystemType")
        'AddAttribute(pXmlClass, "SystemStartupOptions")
        AddAttribute(pXmlClass, "SystemType")
        'AddAttribute(pXmlClass, "ThermalState")
        AddAttribute(pXmlClass, "TotalPhysicalMemory")
        'AddAttribute(pXmlClass, "Workgroup")

        'pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystemProduct")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "IdentifyingNumber")
        'AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "UUID")
        'AddAttribute(pXmlClass, "Vendor")
        'AddAttribute(pXmlClass, "Version")

        'pXmlClass = AddItem(pSystemInfo, "Win32_DesktopMonitor")
        'AddAttribute(pXmlClass, "Availability")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "ScreenHeight")
        'AddAttribute(pXmlClass, "ScreenWidth")

        pXmlClass = AddItem(pSystemInfo, "Win32_DiskDrive")
        'AddAttribute(pXmlClass, "BytesPerSector")
        'AddAttribute(pXmlClass, "Capabilities")
        'AddAttribute(pXmlClass, "CapabilityDescriptions")
        'AddAttribute(pXmlClass, "FirmwareRevision")
        AddAttribute(pXmlClass, "InterfaceType")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Partitions")
        'AddAttribute(pXmlClass, "SectorsPerTrack")
        'AddAttribute(pXmlClass, "SCSIBus")
        'AddAttribute(pXmlClass, "SCSILogicalUnit")
        'AddAttribute(pXmlClass, "SCSIPort")
        'AddAttribute(pXmlClass, "SCSITargetId")
        'AddAttribute(pXmlClass, "SerialNumber")
        'AddAttribute(pXmlClass, "Signature")
        AddAttribute(pXmlClass, "Size")
        'AddAttribute(pXmlClass, "TotalCylinders")
        'AddAttribute(pXmlClass, "TotalHeads")
        'AddAttribute(pXmlClass, "TotalSectors")
        'AddAttribute(pXmlClass, "TotalTracks")
        'AddAttribute(pXmlClass, "TracksPerCylinder")

        'pXmlClass = AddItem(pSystemInfo, "Win32_DisplayConfiguration")
        'AddAttribute(pXmlClass, "BitsPerPel")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DeviceName")
        'AddAttribute(pXmlClass, "DisplayFrequency")
        'AddAttribute(pXmlClass, "DriverVersion")
        'AddAttribute(pXmlClass, "PelsHeight")
        'AddAttribute(pXmlClass, "PelsWidth")

        pXmlClass = AddItem(pSystemInfo, "Win32_FloppyDrive")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_Keyboard")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Layout")
        'AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_LogicalDisk")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DriveType")
        AddAttribute(pXmlClass, "FileSystem")
        AddAttribute(pXmlClass, "FreeSpace")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Size")
        'AddAttribute(pXmlClass, "VolumeName")
        'AddAttribute(pXmlClass, "VolumeSerialNumber")

        'pXmlClass = AddItem(pSystemInfo, "Win32_MemoryDevice")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DeviceID")
        'AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "StartingAddress")
        'AddAttribute(pXmlClass, "EndingAddress")
        'AddAttribute(pXmlClass, "VolumeSerialNumber")

        'pXmlClass = AddItem(pSystemInfo, "Win32_MotherboardDevice")
        'AddItem(pXmlClass, "Description")
        'AddItem(pXmlClass, "Name")
        'AddItem(pXmlClass, "PrimaryBusType")
        'AddItem(pXmlClass, "SecondaryBusType")

        pXmlClass = AddItem(pSystemInfo, "Win32_NetworkAdapter")
        AddAttribute(pXmlClass, "AdapterType")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProductName")
        AddAttribute(pXmlClass, "ServiceName")

        pXmlClass = AddItem(pSystemInfo, "Win32_OperatingSystem")
        AddAttribute(pXmlClass, "BuildNumber")
        'AddAttribute(pXmlClass, "BuildType")
        AddAttribute(pXmlClass, "CSDVersion")
        'AddAttribute(pXmlClass, "EncryptionLevel")
        'AddAttribute(pXmlClass, "InstallDate")
        'AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "OSArchitecture")
        'AddAttribute(pXmlClass, "SerialNumber")
        'AddAttribute(pXmlClass, "ServicePackMajorVersion")
        'AddAttribute(pXmlClass, "ServicePackMinorVersion")
        AddAttribute(pXmlClass, "SystemDirectory")
        'AddAttribute(pXmlClass, "SystemDrive")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_PhysicalMemory")
        AddAttribute(pXmlClass, "BankLabel")
        AddAttribute(pXmlClass, "Capacity")
        'AddAttribute(pXmlClass, "DataWidth")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "FormFactor")
        AddAttribute(pXmlClass, "InterleavePosition")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MemoryType")
        AddAttribute(pXmlClass, "PartNumber")
        'AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "Spedd")
        'AddAttribute(pXmlClass, "TotalWidth")
        'AddAttribute(pXmlClass, "TypeDetail")

        pXmlClass = AddItem(pSystemInfo, "Win32_PointingDevice")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceInterface")
        AddAttribute(pXmlClass, "HardwareType")
        AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_PortableBattery")
        'AddAttribute(pXmlClass, "CapacityMultiplier")
        'AddAttribute(pXmlClass, "Chemistry")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DesignCapacity")
        'AddAttribute(pXmlClass, "DesignVoltage")
        AddAttribute(pXmlClass, "Location")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "SmartBatteryVersion")

        pXmlClass = AddItem(pSystemInfo, "Win32_PortConnector")
        AddAttribute(pXmlClass, "ConnectorType")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "ExternalReferenceDesignator")
        AddAttribute(pXmlClass, "InternalReferenceDesignator")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "PortType")

        pXmlClass = AddItem(pSystemInfo, "Win32_POTSModem")
        AddAttribute(pXmlClass, "AttachedTo")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceType")
        'AddAttribute(pXmlClass, "DriverDate")
        AddAttribute(pXmlClass, "MaxBaudRateToSerialPort")
        'AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProviderName")

        pXmlClass = AddItem(pSystemInfo, "Win32_Printer")
        'AddAttribute(pXmlClass, "Attributes")
        'AddAttribute(pXmlClass, "Capabilities")
        'AddAttribute(pXmlClass, "CapabilityDescriptions")
        AddAttribute(pXmlClass, "DriverName")
        'AddAttribute(pXmlClass, "HorizontalResolution")
        'AddAttribute(pXmlClass, "Local")
        AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "Network")
        'AddAttribute(pXmlClass, "PaperSizesSupported")
        AddAttribute(pXmlClass, "PortName")
        'AddAttribute(pXmlClass, "PrinterPaperNames")
        'AddAttribute(pXmlClass, "PrintProcessor")
        'AddAttribute(pXmlClass, "ServerName")
        'AddAttribute(pXmlClass, "VerticalResolution")

        pXmlClass = AddItem(pSystemInfo, "Win32_Processor")
        'AddAttribute(pXmlClass, "AddressWidth")
        'AddAttribute(pXmlClass, "Architecture")
        'AddAttribute(pXmlClass, "CpuStatus")
        AddAttribute(pXmlClass, "CurrentClockSpeed")
        'AddAttribute(pXmlClass, "CurrentVoltage")
        'AddAttribute(pXmlClass, "DataWidth")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "ExtClock")
        'AddAttribute(pXmlClass, "Family")
        AddAttribute(pXmlClass, "L2CacheSize")
        AddAttribute(pXmlClass, "L2CacheSpeed")
        'AddAttribute(pXmlClass, "Level")
        'AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MaxClockSpeed")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "NumberOfCores")
        AddAttribute(pXmlClass, "NumberOfLogicalProcessors")
        AddAttribute(pXmlClass, "ProcessorId")
        'AddAttribute(pXmlClass, "ProcessorType")
        AddAttribute(pXmlClass, "Revision")
        'AddAttribute(pXmlClass, "SocketDesignation")
        'AddAttribute(pXmlClass, "Stepping")
        'AddAttribute(pXmlClass, "UpgradeMethod")
        'AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_SerialPort")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "MaxBaudRate")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProviderType")

        pXmlClass = AddItem(pSystemInfo, "Win32_SoundDevice")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProductName")

        pXmlClass = AddItem(pSystemInfo, "Win32_SystemEnclosure")
        AddAttribute(pXmlClass, "ChassisTypes")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "SecurityStatus")
        'AddAttribute(pXmlClass, "SerialNumber")
        'AddAttribute(pXmlClass, "SMBIOSAssetTag")
        'AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_SystemSlot")
        'AddAttribute(pXmlClass, "ConnectorType")
        AddAttribute(pXmlClass, "CurrentUsage")
        'AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "MaxDataWidth")
        'AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Number")
        AddAttribute(pXmlClass, "SlotDesignation")
        AddAttribute(pXmlClass, "VccMixedVoltageSupport")

        'pXmlClass = AddItem(pSystemInfo, "Win32_TemperatureProbe")
        'AddAttribute(pXmlClass, "Accuracy")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "MaxReadable")
        'AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "Resolution")
        'AddAttribute(pXmlClass, "Tolerance")

        'pXmlClass = AddItem(pSystemInfo, "Win32_USBController")
        'AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "Manufacturer")
        'AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_VideoController")
        AddAttribute(pXmlClass, "AdapterCompatibility")
        AddAttribute(pXmlClass, "AdapterDACType")
        AddAttribute(pXmlClass, "AdapterRAM")
        'AddAttribute(pXmlClass, "CurrentBitsPerPixel")
        'AddAttribute(pXmlClass, "CurrentHorizontalResolution")
        'AddAttribute(pXmlClass, "CurrentNumberOfColors")
        'AddAttribute(pXmlClass, "CurrentRefreshRate")
        'AddAttribute(pXmlClass, "CurrentScanMode")
        'AddAttribute(pXmlClass, "CurrentVerticalResolution")
        AddAttribute(pXmlClass, "Description")
        'AddAttribute(pXmlClass, "DriverDate")
        'AddAttribute(pXmlClass, "DriverVersion")
        'AddAttribute(pXmlClass, "MaxRefreshRate")
        'AddAttribute(pXmlClass, "MinRefreshRate")
        'AddAttribute(pXmlClass, "VideoArchitecture")
        'AddAttribute(pXmlClass, "VideoMemoryType")
        AddAttribute(pXmlClass, "VideoModeDescription")
        AddAttribute(pXmlClass, "VideoProcessor")

        pXmlClass = AddItem(pSystemInfo, "Win32_Volume")
        'AddAttribute(pXmlClass, "BlockSize")
        AddAttribute(pXmlClass, "Capacity")
        AddAttribute(pXmlClass, "DriveLetter")
        AddAttribute(pXmlClass, "DriveType")
        AddAttribute(pXmlClass, "FileSystem")
        AddAttribute(pXmlClass, "FreeSpace")
        'AddAttribute(pXmlClass, "MaximumFileNameLength")
        AddAttribute(pXmlClass, "Name")
        'AddAttribute(pXmlClass, "SerialNumber")

        Return pXmlDocument
    End Function
    Public Function [Resume]() As XmlDocument
        Dim pXmlDocument As New XmlDocument
        pXmlDocument.AppendChild(pXmlDocument.CreateProcessingInstruction("xml", "version='1.0' encoding='utf-8'"))

        Dim pSystemInfo As XmlElement = pXmlDocument.CreateElement("SystemInfo")
        pSystemInfo.SetAttribute("Type", "Resume")
        pXmlDocument.AppendChild(pSystemInfo)

        Dim pXmlClass As XmlElement
        pXmlClass = AddItem(pSystemInfo, "Win32_Monitor")
        AddAttribute(pXmlClass, "ID")
        AddAttribute(pXmlClass, "Device")
        AddAttribute(pXmlClass, "ManufacturerID")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Serial")

        pXmlClass = AddItem(pSystemInfo, "Win32_1394Controller")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProtocolSupported")

        pXmlClass = AddItem(pSystemInfo, "Win32_BaseBoard")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Product")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_Battery")
        AddAttribute(pXmlClass, "Availability")
        AddAttribute(pXmlClass, "BatteryStatus")
        AddAttribute(pXmlClass, "Chemistry")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DesignCapacity")
        AddAttribute(pXmlClass, "DesignVoltage")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "EstimatedChargeRemaining")
        AddAttribute(pXmlClass, "EstimatedRunTime")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "PowerManagementCapabilities")

        pXmlClass = AddItem(pSystemInfo, "Win32_BIOS")
        AddAttribute(pXmlClass, "BiosCharacteristics")
        AddAttribute(pXmlClass, "BIOSVersion")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ReleaseDate")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "ReleaseDate")
        AddAttribute(pXmlClass, "SMBIOSBIOSVersion")
        AddAttribute(pXmlClass, "SMBIOSMajorVersion")
        AddAttribute(pXmlClass, "SMBIOSMinorVersion")
        AddAttribute(pXmlClass, "SoftwareElementState")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_CacheMemory")
        AddAttribute(pXmlClass, "Associativity")
        AddAttribute(pXmlClass, "Availability")
        AddAttribute(pXmlClass, "BlockSize")
        AddAttribute(pXmlClass, "CacheSpeed")
        AddAttribute(pXmlClass, "CacheType")
        AddAttribute(pXmlClass, "CurrentSRAM")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "ErrorCorrectType")
        AddAttribute(pXmlClass, "InstalledSize")
        AddAttribute(pXmlClass, "Level")
        AddAttribute(pXmlClass, "Location")
        AddAttribute(pXmlClass, "MaxCacheSize")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "NumberOfBlocks")
        AddAttribute(pXmlClass, "Purpose")
        AddAttribute(pXmlClass, "StatusInfo")
        AddAttribute(pXmlClass, "SupportedSRAM")
        AddAttribute(pXmlClass, "WritePolicy")

        pXmlClass = AddItem(pSystemInfo, "Win32_CDROMDrive")
        AddAttribute(pXmlClass, "Availability")
        AddAttribute(pXmlClass, "Capabilities")
        AddAttribute(pXmlClass, "CapabilityDescriptions")
        AddAttribute(pXmlClass, "CompressionMethod")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "Drive")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "SCSIBus")
        AddAttribute(pXmlClass, "SCSILogicalUnit")
        AddAttribute(pXmlClass, "SCSIPort")
        AddAttribute(pXmlClass, "SCSITargetId")

        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystem")
        AddAttribute(pXmlClass, "ChassisBootupState")
        AddAttribute(pXmlClass, "DNSHostName")
        AddAttribute(pXmlClass, "Domain")
        AddAttribute(pXmlClass, "InfraredSupported")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "NumberOfLogicalProcessors")
        AddAttribute(pXmlClass, "NumberOfProcessors")
        AddAttribute(pXmlClass, "OEMStringArray")
        AddAttribute(pXmlClass, "PCSystemType")
        AddAttribute(pXmlClass, "SystemStartupOptions")
        AddAttribute(pXmlClass, "SystemType")
        AddAttribute(pXmlClass, "ThermalState")
        AddAttribute(pXmlClass, "TotalPhysicalMemory")
        AddAttribute(pXmlClass, "Workgroup")

        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystemProduct")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "IdentifyingNumber")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "UUID")
        AddAttribute(pXmlClass, "Vendor")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_DesktopMonitor")
        AddAttribute(pXmlClass, "Availability")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ScreenHeight")
        AddAttribute(pXmlClass, "ScreenWidth")

        pXmlClass = AddItem(pSystemInfo, "Win32_DiskDrive")
        AddAttribute(pXmlClass, "BytesPerSector")
        AddAttribute(pXmlClass, "Capabilities")
        AddAttribute(pXmlClass, "CapabilityDescriptions")
        AddAttribute(pXmlClass, "FirmwareRevision")
        AddAttribute(pXmlClass, "InterfaceType")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Partitions")
        AddAttribute(pXmlClass, "SectorsPerTrack")
        AddAttribute(pXmlClass, "SCSIBus")
        AddAttribute(pXmlClass, "SCSILogicalUnit")
        AddAttribute(pXmlClass, "SCSIPort")
        AddAttribute(pXmlClass, "SCSITargetId")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "Signature")
        AddAttribute(pXmlClass, "Size")
        AddAttribute(pXmlClass, "TotalCylinders")
        AddAttribute(pXmlClass, "TotalHeads")
        AddAttribute(pXmlClass, "TotalSectors")
        AddAttribute(pXmlClass, "TotalTracks")
        AddAttribute(pXmlClass, "TracksPerCylinder")

        pXmlClass = AddItem(pSystemInfo, "Win32_DisplayConfiguration")
        AddAttribute(pXmlClass, "BitsPerPel")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceName")
        AddAttribute(pXmlClass, "DisplayFrequency")
        AddAttribute(pXmlClass, "DriverVersion")
        AddAttribute(pXmlClass, "PelsHeight")
        AddAttribute(pXmlClass, "PelsWidth")

        pXmlClass = AddItem(pSystemInfo, "Win32_FloppyDrive")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_Keyboard")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Layout")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_LogicalDisk")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DriveType")
        AddAttribute(pXmlClass, "FileSystem")
        AddAttribute(pXmlClass, "FreeSpace")
        AddAttribute(pXmlClass, "MediaType")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Size")
        AddAttribute(pXmlClass, "VolumeName")
        AddAttribute(pXmlClass, "VolumeSerialNumber")

        pXmlClass = AddItem(pSystemInfo, "Win32_MemoryDevice")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "EndingAddress")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "StartingAddress")
        AddAttribute(pXmlClass, "VolumeSerialNumber")

        'pXmlClass = AddItem(pSystemInfo, "Win32_MotherboardDevice")
        'AddItem(pXmlClass, "Description")
        'AddItem(pXmlClass, "Name")
        'AddItem(pXmlClass, "PrimaryBusType")
        'AddItem(pXmlClass, "SecondaryBusType")

        pXmlClass = AddItem(pSystemInfo, "Win32_NetworkAdapter")
        AddAttribute(pXmlClass, "AdapterType")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProductName")
        AddAttribute(pXmlClass, "ServiceName")

        pXmlClass = AddItem(pSystemInfo, "Win32_OperatingSystem")
        AddAttribute(pXmlClass, "BuildNumber")
        AddAttribute(pXmlClass, "BuildType")
        AddAttribute(pXmlClass, "CSDVersion")
        AddAttribute(pXmlClass, "EncryptionLevel")
        AddAttribute(pXmlClass, "InstallDate")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "OSArchitecture")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "ServicePackMajorVersion")
        AddAttribute(pXmlClass, "ServicePackMinorVersion")
        AddAttribute(pXmlClass, "SystemDirectory")
        AddAttribute(pXmlClass, "SystemDrive")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_PhysicalMemory")
        AddAttribute(pXmlClass, "BankLabel")
        AddAttribute(pXmlClass, "Capacity")
        AddAttribute(pXmlClass, "DataWidth")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "FormFactor")
        AddAttribute(pXmlClass, "InterleavePosition")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MemoryType")
        AddAttribute(pXmlClass, "PartNumber")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "Spedd")
        AddAttribute(pXmlClass, "TotalWidth")
        AddAttribute(pXmlClass, "TypeDetail")

        pXmlClass = AddItem(pSystemInfo, "Win32_PointingDevice")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceInterface")
        AddAttribute(pXmlClass, "HardwareType")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_PortableBattery")
        AddAttribute(pXmlClass, "CapacityMultiplier")
        AddAttribute(pXmlClass, "Chemistry")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DesignCapacity")
        AddAttribute(pXmlClass, "DesignVoltage")
        AddAttribute(pXmlClass, "Location")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "SmartBatteryVersion")

        pXmlClass = AddItem(pSystemInfo, "Win32_PortConnector")
        AddAttribute(pXmlClass, "ConnectorType")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "ExternalReferenceDesignator")
        AddAttribute(pXmlClass, "InternalReferenceDesignator")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "PortType")

        pXmlClass = AddItem(pSystemInfo, "Win32_POTSModem")
        AddAttribute(pXmlClass, "AttachedTo")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceType")
        AddAttribute(pXmlClass, "DriverDate")
        AddAttribute(pXmlClass, "MaxBaudRateToSerialPort")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProviderName")

        pXmlClass = AddItem(pSystemInfo, "Win32_Printer")
        AddAttribute(pXmlClass, "Attributes")
        AddAttribute(pXmlClass, "Capabilities")
        AddAttribute(pXmlClass, "CapabilityDescriptions")
        AddAttribute(pXmlClass, "DriverName")
        AddAttribute(pXmlClass, "HorizontalResolution")
        AddAttribute(pXmlClass, "Local")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Network")
        AddAttribute(pXmlClass, "PaperSizesSupported")
        AddAttribute(pXmlClass, "PortName")
        AddAttribute(pXmlClass, "PrinterPaperNames")
        AddAttribute(pXmlClass, "PrintProcessor")
        AddAttribute(pXmlClass, "ServerName")
        AddAttribute(pXmlClass, "VerticalResolution")

        pXmlClass = AddItem(pSystemInfo, "Win32_Processor")
        AddAttribute(pXmlClass, "AddressWidth")
        AddAttribute(pXmlClass, "Architecture")
        AddAttribute(pXmlClass, "CpuStatus")
        AddAttribute(pXmlClass, "CurrentClockSpeed")
        AddAttribute(pXmlClass, "CurrentVoltage")
        AddAttribute(pXmlClass, "DataWidth")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "ExtClock")
        AddAttribute(pXmlClass, "Family")
        AddAttribute(pXmlClass, "L2CacheSize")
        AddAttribute(pXmlClass, "L2CacheSpeed")
        AddAttribute(pXmlClass, "Level")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "MaxClockSpeed")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "NumberOfCores")
        AddAttribute(pXmlClass, "NumberOfLogicalProcessors")
        AddAttribute(pXmlClass, "ProcessorId")
        AddAttribute(pXmlClass, "ProcessorType")
        AddAttribute(pXmlClass, "Revision")
        AddAttribute(pXmlClass, "SocketDesignation")
        AddAttribute(pXmlClass, "Stepping")
        AddAttribute(pXmlClass, "UpgradeMethod")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_SerialPort")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DeviceID")
        AddAttribute(pXmlClass, "MaxBaudRate")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProviderType")

        pXmlClass = AddItem(pSystemInfo, "Win32_SoundDevice")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "ProductName")

        pXmlClass = AddItem(pSystemInfo, "Win32_SystemEnclosure")
        AddAttribute(pXmlClass, "ChassisTypes")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Model")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "SecurityStatus")
        AddAttribute(pXmlClass, "SerialNumber")
        AddAttribute(pXmlClass, "SMBIOSAssetTag")
        AddAttribute(pXmlClass, "Version")

        pXmlClass = AddItem(pSystemInfo, "Win32_SystemSlot")
        AddAttribute(pXmlClass, "ConnectorType")
        AddAttribute(pXmlClass, "CurrentUsage")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "MaxDataWidth")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Number")
        AddAttribute(pXmlClass, "SlotDesignation")
        AddAttribute(pXmlClass, "VccMixedVoltageSupport")

        pXmlClass = AddItem(pSystemInfo, "Win32_TemperatureProbe")
        AddAttribute(pXmlClass, "Accuracy")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "MaxReadable")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "Resolution")
        AddAttribute(pXmlClass, "Tolerance")

        pXmlClass = AddItem(pSystemInfo, "Win32_USBController")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "Manufacturer")
        AddAttribute(pXmlClass, "Name")

        pXmlClass = AddItem(pSystemInfo, "Win32_VideoController")
        AddAttribute(pXmlClass, "AdapterCompatibility")
        AddAttribute(pXmlClass, "AdapterDACType")
        AddAttribute(pXmlClass, "AdapterRAM")
        AddAttribute(pXmlClass, "CurrentBitsPerPixel")
        AddAttribute(pXmlClass, "CurrentHorizontalResolution")
        AddAttribute(pXmlClass, "CurrentNumberOfColors")
        AddAttribute(pXmlClass, "CurrentRefreshRate")
        AddAttribute(pXmlClass, "CurrentScanMode")
        AddAttribute(pXmlClass, "CurrentVerticalResolution")
        AddAttribute(pXmlClass, "Description")
        AddAttribute(pXmlClass, "DriverDate")
        AddAttribute(pXmlClass, "DriverVersion")
        AddAttribute(pXmlClass, "MaxRefreshRate")
        AddAttribute(pXmlClass, "MinRefreshRate")
        AddAttribute(pXmlClass, "VideoArchitecture")
        AddAttribute(pXmlClass, "VideoMemoryType")
        AddAttribute(pXmlClass, "VideoModeDescription")
        AddAttribute(pXmlClass, "VideoProcessor")

        pXmlClass = AddItem(pSystemInfo, "Win32_Volume")
        AddAttribute(pXmlClass, "BlockSize")
        AddAttribute(pXmlClass, "Capacity")
        AddAttribute(pXmlClass, "DriveLetter")
        AddAttribute(pXmlClass, "DriveType")
        AddAttribute(pXmlClass, "FileSystem")
        AddAttribute(pXmlClass, "FreeSpace")
        AddAttribute(pXmlClass, "MaximumFileNameLength")
        AddAttribute(pXmlClass, "Name")
        AddAttribute(pXmlClass, "SerialNumber")

        Return pXmlDocument
    End Function
    Public Function Complete() As XmlDocument
        Dim pXmlDocument As New XmlDocument
        pXmlDocument.AppendChild(pXmlDocument.CreateProcessingInstruction("xml", "version='1.0' encoding='utf-8'"))

        Dim pSystemInfo As XmlElement = pXmlDocument.CreateElement("SystemInfo")
        pSystemInfo.SetAttribute("Type", "Complete")
        pXmlDocument.AppendChild(pSystemInfo)

        Dim pXmlClass As XmlElement
        pXmlClass = AddItem(pSystemInfo, "Win32_Monitor")
        pXmlClass = AddItem(pSystemInfo, "Win32_1394Controller")
        pXmlClass = AddItem(pSystemInfo, "Win32_1394ControllerDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_BaseBoard")
        pXmlClass = AddItem(pSystemInfo, "Win32_Battery")
        pXmlClass = AddItem(pSystemInfo, "Win32_BIOS")
        pXmlClass = AddItem(pSystemInfo, "Win32_CacheMemory")
        pXmlClass = AddItem(pSystemInfo, "Win32_CDROMDrive")
        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystem")
        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystemProcessor")
        pXmlClass = AddItem(pSystemInfo, "Win32_ComputerSystemProduct")
        pXmlClass = AddItem(pSystemInfo, "Win32_DesktopMonitor")
        pXmlClass = AddItem(pSystemInfo, "Win32_DiskDrive")
        pXmlClass = AddItem(pSystemInfo, "Win32_DisplayConfiguration")
        pXmlClass = AddItem(pSystemInfo, "Win32_FloppyController")
        pXmlClass = AddItem(pSystemInfo, "Win32_FloppyDrive")
        pXmlClass = AddItem(pSystemInfo, "Win32_InfraredDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_Keyboard")
        pXmlClass = AddItem(pSystemInfo, "Win32_LocalTime")
        pXmlClass = AddItem(pSystemInfo, "Win32_LogicalDisk")
        pXmlClass = AddItem(pSystemInfo, "Win32_MemoryDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_MotherboardDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_NetworkAdapter")
        pXmlClass = AddItem(pSystemInfo, "Win32_NetworkAdapterConfiguration")
        pXmlClass = AddItem(pSystemInfo, "Win32_OperatingSystem")
        pXmlClass = AddItem(pSystemInfo, "Win32_PhysicalMedia")
        pXmlClass = AddItem(pSystemInfo, "Win32_PhysicalMemory")
        pXmlClass = AddItem(pSystemInfo, "Win32_PointingDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_PortableBattery")
        pXmlClass = AddItem(pSystemInfo, "Win32_PortConnector")
        pXmlClass = AddItem(pSystemInfo, "Win32_POTSModem")
        pXmlClass = AddItem(pSystemInfo, "Win32_Printer")
        pXmlClass = AddItem(pSystemInfo, "Win32_PrinterController")
        pXmlClass = AddItem(pSystemInfo, "Win32_Processor")
        pXmlClass = AddItem(pSystemInfo, "Win32_Refrigeration")
        pXmlClass = AddItem(pSystemInfo, "Win32_SerialPort")
        pXmlClass = AddItem(pSystemInfo, "Win32_SerialPortConfiguration")
        pXmlClass = AddItem(pSystemInfo, "Win32_SerialPortSetting")
        pXmlClass = AddItem(pSystemInfo, "Win32_SoundDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_SystemEnclosure")
        pXmlClass = AddItem(pSystemInfo, "Win32_SystemSlot")
        pXmlClass = AddItem(pSystemInfo, "Win32_TapeDrive")
        pXmlClass = AddItem(pSystemInfo, "Win32_TCPIPPrinterPort")
        pXmlClass = AddItem(pSystemInfo, "Win32_TemperatureProbe")
        pXmlClass = AddItem(pSystemInfo, "Win32_TimeZone")
        pXmlClass = AddItem(pSystemInfo, "Win32_USBController")
        pXmlClass = AddItem(pSystemInfo, "Win32_USBControllerDevice")
        pXmlClass = AddItem(pSystemInfo, "Win32_USBHub")
        pXmlClass = AddItem(pSystemInfo, "Win32_UTCTime")
        pXmlClass = AddItem(pSystemInfo, "Win32_VideoController")
        pXmlClass = AddItem(pSystemInfo, "Win32_VoltageProbe")
        pXmlClass = AddItem(pSystemInfo, "Win32_Volume")

        Return pXmlDocument
    End Function

    Private Function AddClass(ByRef pXmlDocument As XmlDocument, ByVal pClass As String) As XmlElement
        Dim pXmlClass As XmlElement = pXmlDocument.CreateElement(pClass)
        pXmlDocument.DocumentElement.AppendChild(pXmlClass)
        Return pXmlClass
    End Function
    Private Function AddItem(ByRef pXmlElement As XmlElement, ByVal pName As String) As XmlElement
        Dim pXmlClass As XmlElement = pXmlElement.OwnerDocument.CreateElement(pName)
        pXmlElement.AppendChild(pXmlClass)
        Return pXmlClass
    End Function
    Private Function AddAttribute(ByRef pXmlElement As XmlElement, ByVal pName As String) As XmlAttribute
        Dim pXmlAttribute As XmlAttribute = pXmlElement.OwnerDocument.CreateAttribute(pName)
        pXmlElement.Attributes.Append(pXmlAttribute)
        Return pXmlAttribute
    End Function
End Module
